### PR TITLE
fix: Support Nexus 1.0.0 (#182)

### PR DESCRIPTION
**Pull request by lewebsimple**
I updated the package name and changed `RootValue` to `SourceValue` and all tests are passing !

Could it be this simple ?!

### CODE REVIEW

**Comment by lewebsimple** [comment]
It seems to work just fine in one of my projects that was updated to nexus 1.0.0 !

**Comment by Sytten** [comment]
Thanks for that, I will pull it locally just to make sure. I think it might warrant a minor version upgrade instead of a fix.
Should be merged by the end of the day.

**Comment by lewebsimple** [comment]
@Sytten did you want to release this with a minor version bump or are you still waiting for other features / bugfixes ?

**Comment by Sytten** [comment]
Sorry for the delay I had a rough week and enjoying some time off. I will finish everything tomorrow.

**Comment by Sytten** [comment]
Fixed by #190

**Pull request closed without merging**
